name: ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^3.1.0
  provider: ^6.1.2
  firebase_auth: ^5.1.0
  video_player: ^2.8.7
  shared_preferences: ^2.3.1
  flutter_gemini: ^2.0.4
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  flutter_rating_bar: ^4.0.1
  confetti: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  camera: ^0.11.0+2
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/images/

# Section for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "asset/images/logo-color.png"
  min_sdk_android: 23
