// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbfSgHA8CNY9WZDBChABSEaNgtJgeDSH4',
    appId: '1:149328729023:web:03fbcfcb42395ba3ad870a',
    messagingSenderId: '149328729023',
    projectId: 'ecommerce-6f3bf',
    authDomain: 'ecommerce-6f3bf.firebaseapp.com',
    storageBucket: 'ecommerce-6f3bf.appspot.com',
    measurementId: 'G-0PE166WZ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqpvHTywd_ATeKJ8PzCPNANaRMmDyBXig',
    appId: '1:149328729023:android:9edd82ad78fc5509ad870a',
    messagingSenderId: '149328729023',
    projectId: 'ecommerce-6f3bf',
    storageBucket: 'ecommerce-6f3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB371pNl3Y3pMt9T3dSvUrxfoQkvudcLlA',
    appId: '1:149328729023:ios:9b2d0371d9d86d18ad870a',
    messagingSenderId: '149328729023',
    projectId: 'ecommerce-6f3bf',
    storageBucket: 'ecommerce-6f3bf.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB371pNl3Y3pMt9T3dSvUrxfoQkvudcLlA',
    appId: '1:149328729023:ios:9b2d0371d9d86d18ad870a',
    messagingSenderId: '149328729023',
    projectId: 'ecommerce-6f3bf',
    storageBucket: 'ecommerce-6f3bf.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbfSgHA8CNY9WZDBChABSEaNgtJgeDSH4',
    appId: '1:149328729023:web:8ed106e8babaea01ad870a',
    messagingSenderId: '149328729023',
    projectId: 'ecommerce-6f3bf',
    authDomain: 'ecommerce-6f3bf.firebaseapp.com',
    storageBucket: 'ecommerce-6f3bf.appspot.com',
    measurementId: 'G-ZWM5K65JSM',
  );
}
